import { Lora } from "next/font/google";
import "./globals.css";
import Navebar from "./_components/Header/Navebar/navebar";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "./_components/Footer/footer";
import NextTopLoader from "nextjs-toploader";

const lora = Lora({ subsets: ["latin"] });

export const metadata = {
  title: "Blog Horizon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navebar />
          <NextTopLoader
            color="#bc52c8"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 1px #2299DD,0 0 1px #2299DD"
            template='<div class="bar" role="bar"><div class="peg"></div></div> 
            <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
            zIndex={1600}
            showAtBottom={false}
          />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
